name: DevDeploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --configuration=production

      - name: Deploy
        run: |
          # Install sshpass
          sudo apt-get install -y sshpass

          # Deploy using username and password with StrictHostKeyChecking disabled
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r dist/* ${{ secrets.DEV_USER }}@${{ secrets.DEPLOY_SERVER }}:${{ secrets.PATH_TO_DEV_DIRECTORY }}
